### ISSUE TITLE
[alpha] "ReferenceError: document is not defined" when importing an HTML-based module into the REPL 

### ISSUE THREAD

**Issue by clarkware** [elm-lang/elm-repl#135]
Elm 0.18.0
Mac OS X Version 10.11.6
Node.js v5.4.0

Given the following Elm code that generates HTML:

```elm
module Hello exposing (..)

import Html exposing (text)

main =
    text "Hello, World!"
```

Importing the module in the REPL gives the following error:

```elm
> import Hello
/path/to/repl-temp-000.js:5703
var localDoc = document;
               ^

ReferenceError: document is not defined
    at /path/to/repl-temp-000.js:5703:16
    at Object.<anonymous> (/path/to/repl-temp-000.js:7748:2)
    at Object.<anonymous> (/path/to/repl-temp-000.js:7946:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

**Comment by evancz** [comment]
Thanks for the report! If you delete `elm-stuff/` and try again it should be fixed!

**Comment by clarkware** [comment]
Indeed, that fixed it. Thanks!
